//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFEngine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunDetail
    {
        public int ReportId { get; set; }
        public Nullable<int> RunId { get; set; }
        public byte[] ReportBLOB { get; set; }
        public string ReportDescription { get; set; }
        public Nullable<int> ReportFilter { get; set; }
    }
}
